name: verify

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: setup-go
        uses: actions/setup-go@v3
        with:
          go-version: 'stable'

      - name: setup-osquery
        run: |
         curl -LO https://pkg.osquery.io/deb/osquery_5.7.0-1.linux_amd64.deb
         sudo dpkg -i osquery_5.7.0-1.linux_amd64.deb

      - name: verify
        run: ./sunlight.sh

